### ISSUE TITLE
Setting and End Date to the Calendar

### ISSUE THREAD

**Issue by Azhang9999** [ziyaointl/Schedule-Exporter#2]
After trying out this extension I found it to be immensely helpful. However, when I import it into Google Calendar, the dates keep going until forever. I'm wondering if it's possible to continue the events until the end of semester, and not have it go on beyond the end of the semester.

**Comment by ziyaointl** [comment]
Thanks for your suggestion! This functionality has been added in v1.2.0, which is still under Google's review but can be manually found in the Github releases section.
