### ISSUE TITLE
Cannot handle onsite classes

### ISSUE THREAD

**Issue by tarawa** [ziyaointl/Schedule-Exporter#4]
In the function `parseTable`, the `return` function cannot parse the onsite courses correctly.

After lines 
```js
let matches = [...target.matchAll(/> (.*) - (.*)$/g)][0]
startTime = matches[1], endTime = matches[2]
```

The `startTime` would become `"2:00pm - 3:29pm"` and the `endTime` would become location `"Stanley 179"`

**Comment by ziyaointl** [comment]
Thank you very much! I updated the master branch with a fix. Chrome web store takes a couple of days to for the new version to get approved. In the meanwhile, feel free to download the source and load it manually if you'd like.
