### ISSUE TITLE
No response after clicking on the extension icon

### ISSUE THREAD

**Issue by Qinggao1729** [ziyaointl/Schedule-Exporter#5]
I go to the schedule planner (the new link is [https://berkeley.collegescheduler.com/entry](url)), select courses from the current schedule, but there's no reponse after clicking on the google extension icon.

**Comment by ziyaointl** [comment]
@Qinggao1729 Thanks for opening an issue! Unfortuantely I have graduated from Berkeley and no longer have access to the scheduler. If you are a developer and have some free time to fix this, feel free to open a pull request. I'll also make a post on reddit to see if anyone is interested in maintaining this application.

**Comment by ziyaointl** [comment]
Closed by #6
