### ISSUE TITLE
Clicking extension icon doesn't do anything

### ISSUE THREAD

**Issue by CNisperos** [ziyaointl/Schedule-Exporter#7]
Hello, I tried using this extension but nothing happened when I tried to use it for this upcoming spring 2023 semester. Any potential debugging fixes?

**Comment by ziyaointl** [comment]
Sorry for the late reply! I just updated the semester dates for Spring 2023 on GitHub. Unfortunately I have already graduated and thus cannot test the extension myself. Could you follow the following instructions to install the extension from GitHub and let me know if it works? I'll update the chrome webstore version if it does.

> If you want to install from source, download the repo as a zip file. Go to chrome://extensions, enable developer mode, select import, and select the folder extracted from the zip file.

**Comment by Gogotron** [comment]
I just tried it out, it works.

**Comment by Qinggao1729** [comment]
It works, thank you. 
BTW, the start date and end date should be Jan 17 and Apr 28.

**Comment by ziyaointl** [comment]
Thanks everyone for testing this! I added more dates until 2029 and published the new version on chrome webstore.
